version: '3.8'

services:
  app:
    image: ghcr.io/dingyufei615/ai-goofish:latest
    container_name: ai-goofish-monitor-app
    pull_policy: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
